name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Debug Firebase Token
      run: echo "Token Length: ${#FIREBASE_SECRETORY}"
      env:
        FIREBASE_SECRETORY: ${{ secrets.FIREBASE_SECRETORY }}

    - name: Deploy to Firebase
      run: firebase deploy --token "${{ secrets.FIREBASE_SECRETORY}}" --debug