name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Validate Secret
      run: echo "${{ secrets.FIREBASE_SECRETORY }}" | wc -c

    #- name: Deploy to Firebase
     # run: firebase deploy --token "${{ secrets.FIREBASE_SECRETORY }}" --debug